### Étape n°2 : Nettoyage et préparation des données

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_anim = pd.read_csv('data/df_anim.csv')
df_pop = pd.read_csv('data/df_pop.csv')
df_veg = pd.read_csv('data/df_veg.csv')

1. Nettoyer les titres de colonnes :
Supprimer les espaces au début et à la fin des titres (s’il y en a)
Remplacer les espaces par des underscores (ceux se situant entre les mots)
Tout mettre en minuscule

In [5]:
for df in [df_anim, df_pop, df_veg]:
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

,code_domaine,domaine,code_zone_(fao),zone,code_élément,élément,code_produit_(fao),produit,code_année,année,unité,valeur,symbole,description_du_symbole
0,FBS,Bilans Alimentaires (2010-),2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2018,2018,kg,2.62,E,Valeur estimée
1,FBS,Bilans Alimentaires (2010-),2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2019,2019,kg,2.73,E,Valeur estimée
2,FBS,Bilans Alimentaires (2010-),2,Afghanistan,661,Disponibilité alimentaire (Kcal),2731,Viande de Bovins,2018,2018,million kcal,209191.00,I,Valeur imputée
3,FBS,Bilans Alimentaires (2010-),2,Afghanistan,661,Disponibilité alimentaire (Kcal),2731,Viande de Bovins,2019,2019,million kcal,222521.90,I,Valeur imputée
4,FBS,Bilans Alimentaires (2010-),2,Afghanistan,674,Disponibilité de protéines en quantité (g/pers...,2731,Viande de Bovins,2018,2018,g/personne/jour,1.09,E,Valeur estimée

3 .Quelle sont les dimensions des jeux de données ?

In [6]:
for df in [df_anim, df_pop, df_veg]:
    print(df.shape)

(31542, 14)
(366, 14)
(93458, 14)

4 . Pour les datasets df_anim et df_veg, ajoutez une colonne ‘type’ qui prendra respectivement une valeur ‘animal’ et ‘vegetal’. Une fois cette étape effectuée, regroupez les deux jeux de données en 1 et appelez ce DataFrame product. Attention à bien comprendre la structure des données pour utiliser la bonne méthode.

In [17]:
df_anim['type'] = 'animal'
df_veg['type'] = 'vegetation'
df_produit = pd.concat([df_anim, df_veg], axis=0)
df_produit

,code_domaine,domaine,code_zone_(fao),zone,code_élément,élément,code_produit_(fao),produit,code_année,année,unité,valeur,symbole,description_du_symbole,type
0,FBS,Bilans Alimentaires (2010-),2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2018,2018,kg,2.62,E,Valeur estimée,animal
1,FBS,Bilans Alimentaires (2010-),2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2019,2019,kg,2.73,E,Valeur estimée,animal
2,FBS,Bilans Alimentaires (2010-),2,Afghanistan,661,Disponibilité alimentaire (Kcal),2731,Viande de Bovins,2018,2018,million kcal,209191.00,I,Valeur imputée,animal
3,FBS,Bilans Alimentaires (2010-),2,Afghanistan,661,Disponibilité alimentaire (Kcal),2731,Viande de Bovins,2019,2019,million kcal,222521.90,I,Valeur imputée,animal
4,FBS,Bilans Alimentaires (2010-),2,Afghanistan,674,Disponibilité de protéines en quantité (g/pers...,2731,Viande de Bovins,2018,2018,g/personne/jour,1.09,E,Valeur estimée,animal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93453,FBS,Bilans Alimentaires (2010-),181,Zimbabwe,661,Disponibilité alimentaire (Kcal),2899,Miscellanees,2019,2019,million kcal,15718.43,I,Valeur imputée,vegetation
93454,FBS,Bilans Alimentaires (2010-),181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2018,2018,g/personne/jour,0.04,E,Valeur estimée,vegetation
93455,FBS,Bilans Alimentaires (2010-),181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2019,2019,g/personne/jour,0.09,E,Valeur estimée,vegetation
93456,FBS,Bilans Alimentaires (2010-),181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2018,2018,g/personne/jour,0.01,E,Valeur estimée,vegetation
93457,FBS,Bilans Alimentaires (2010-),181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2019,2019,g/personne/jour,0.04,E,Valeur estimée,vegetation

5 .Transformez products afin de ne garder que les colonnes area_code_(fao), area, element, item, year, type, unit, value.

In [35]:
df_produit = df_produit[df_produit['zone'] != 'Chine - continentale']
df_produit = df_produit[df_produit['zone'] != 'Chine - Taiwan Province de']
df_produit = df_produit[df_produit['zone'] != 'Chine - RAS de Hong-Kong']
df_produit = df_produit[df_produit['zone'] != 'Chine - RAS de Macao']

               zone  population
0       Afghanistan    37172.00
1       Afghanistan    38041.75
2    Afrique du Sud    57793.00
3    Afrique du Sud    58558.27
4           Albanie     2883.00
..              ...         ...
361           Yémen    29161.92
362          Zambie    17352.00
363          Zambie    17861.03
364        Zimbabwe    14438.80
365        Zimbabwe    14645.47

[366 rows x 2 columns]